// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6isHc3jj1UVHd3mdZ59AjJdKA0oNH0Ao',
    appId: '1:738024841992:web:6fc1a55646cbf13dbf02bd',
    messagingSenderId: '738024841992',
    projectId: 'tabiu-f4f04',
    authDomain: 'tabiu-f4f04.firebaseapp.com',
    storageBucket: 'tabiu-f4f04.firebasestorage.app',
    measurementId: 'G-6BJLDTY4QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8dCQPfVZfCZCGgiI2QpcmrUBsERgR_c8',
    appId: '1:738024841992:android:4271d41479a5dae2bf02bd',
    messagingSenderId: '738024841992',
    projectId: 'tabiu-f4f04',
    storageBucket: 'tabiu-f4f04.firebasestorage.app',
  );
}
